---
- name: download latest stable redis
  get_url: url=http://download.redis.io/redis-stable.tar.gz dest=/tmp/redis-stable.tar.gz

- name: untar redis
  command: tar zxf /tmp/redis-stable.tar.gz -C /tmp

- name: build redis
  command: make -C /tmp/redis-stable

- name: create redis group
  group: name=redis state=present system=yes

- name: create redis user
  user: name=redis group=redis createhome=no shell=/bin/false system=yes state=present

- name: make sure that /etc/redis exists
  file: path=/etc/redis state=directory mode=0755

- name: make sure that /var/db/redis exists
  file: path=/var/db/redis state=directory mode=0755 group=redis owner=redis

- name: make sure redis.log file exists
  copy: src=redis.log dest=/var/log/redis.log owner=redis group=redis mode=0644

- name: copy upstart file
  copy: src=redis-upstart.conf dest=/etc/init/redis.conf

- name: copy redis.conf file
  copy: src=redis.conf dest=/etc/redis/redis.conf group=redis owner=redis

- name: copy logrotate file
  copy: src=redis.logrotate dest=/etc/logrotate.d/redis mode=0644 owner=root group=root

- name: copy custom template
  template: src=redis.local.conf.j2 dest=/etc/redis/redis.local.conf group=redis owner=redis

- name: copy redis-local script
  template: src=redis-local.j2 dest=/usr/local/bin/redis-local mode=0755

- name: stop redis if already running
  service: name=redis state=stopped

- name: installing redis binaries
  command: cp /tmp/redis-stable/src/{{ item }} /usr/local/bin
  with_items:
    - redis-server
    - redis-cli
    - redis-check-aof
    - redis-check-dump
    - redis-benchmark

- name: ensure redis service is restarted
  service: name=redis state=restarted

