---
- hosts: all
  user: vagrant
  sudo: yes
  vars_files:
    - vars.yml
    # - roles/ansible-elasticsearch/vars/vagrant.yml
  roles:
    - common
    - redis
    - postgres
    - nginx
    - rails
    - nodejs
