---
- name: checking installed version of node.js
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = v{{node_version}}
  register: wanted_version_installed
  ignore_errors: True

- name: fetching node.js source
  action: get_url url=http://nodejs.org/dist/v{{node_version}}/{{node_tarball}} dest=/tmp/
  when: wanted_version_installed.rc == 1

- name: unpack node.js tarball
  command: tar zxf {{node_tarball}} chdir=/tmp
  when: wanted_version_installed.rc == 1

- name: configure node.js
  shell: /usr/bin/python ./configure --prefix={{node_path}} chdir=/tmp/{{node_prefix}}
  when: wanted_version_installed.rc == 1

- name: make node.js
  shell: /usr/bin/make chdir=/tmp/{{node_prefix}}/
  when: wanted_version_installed.rc == 1

- name: install node.js
  shell: /usr/bin/make install chdir=/tmp/{{node_prefix}}/
  when: wanted_version_installed.rc == 1
