# Main core playbook
---
- name: ensure apt package cache is up to date
  apt: update_cache=yes
- name: ensure ntp is installed
  apt: pkg=ntp state=installed
  tags: ntp
- name: ensure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp
- name: set time zone to UTC
  copy: content='UTC'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - update timezone
- name: Ensure numerous packages are present
  apt: pkg={{ item }} state=latest
  with_items:
    - "{{ system_packages }}"
